# Generated by Django 6.0.4 on 2026-05-14 12:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                (
                    "description",
                    models.TextField(
                        max_length=2000, verbose_name="Contenu du commentaire"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contributor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Intitulé du problème"
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                (
                    "description",
                    models.TextField(
                        max_length=1500, verbose_name="Description du problème"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("TODO", "To do"),
                            ("PROGRESS", "In progress"),
                            ("FINISH", "Finished"),
                        ],
                        default="TODO",
                        max_length=11,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                        ],
                        max_length=6,
                        verbose_name="Priorité",
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        choices=[
                            ("BUG", "Bug"),
                            ("FEATURE", "Feature"),
                            ("TASK", "Task"),
                        ],
                        max_length=7,
                        verbose_name="Balise",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nom du projet"
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                (
                    "description",
                    models.TextField(
                        max_length=1500, verbose_name="Description du projet"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("BACK", "Back-end"),
                            ("FRONT", "Front-end"),
                            ("IOS", "iOS"),
                            ("ANDROID", "Android"),
                        ],
                        max_length=7,
                        verbose_name="Type de projet",
                    ),
                ),
            ],
        ),
    ]
