# Generated by Django 6.0.4 on 2026-05-06 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contributor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nom du projet"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        max_length=1500, verbose_name="Description du projet"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("BACK", "Back-end"),
                            ("FRONT", "Front-end"),
                            ("IOS", "iOS"),
                            ("ANDROID", "Android"),
                        ],
                        max_length=7,
                        verbose_name="Type de projet",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="issues.contributor",
                        verbose_name="Auteur du projet",
                    ),
                ),
                (
                    "contributors",
                    models.ManyToManyField(
                        related_name="contributed_projects",
                        to="issues.contributor",
                        verbose_name="Contributeurs du projet",
                    ),
                ),
            ],
        ),
    ]
