# Generated by Django 6.0.4 on 2026-05-12 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0002_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="contributor",
            unique_together=set(),
        ),
    ]
