# Generated by Django 6.0.4 on 2026-05-13 14:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0003_alter_contributor_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="uuid",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
    ]
