# Generated by Django 6.0.4 on 2026-05-14 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0004_alter_comment_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_contributor",
                to="issues.contributor",
                verbose_name="Attribution",
            ),
        ),
    ]
